"""Markdown report generation for Spack PR build results."""

from __future__ import annotations

from typing import Iterable, List

from .domain import BuildResult, TaskStatus


def generate_markdown_report(results: Iterable[BuildResult]) -> str:
    """Generate a deterministic markdown summary for local review."""

    results_list = sorted(list(results), key=lambda result: result.task_id)
    passed = [result for result in results_list if result.status == TaskStatus.PASSED]
    failed = [result for result in results_list if result.status == TaskStatus.FAILED]
    skipped = [result for result in results_list if result.status == TaskStatus.SKIPPED]

    lines: List[str] = [
        "`spack install` verification report",
        "",
        f"- Passed: {len(passed)}",
        f"- Failed: {len(failed)}",
        f"- Skipped: {len(skipped)}",
        "",
    ]
    if passed:
        lines.extend(["Passed specs:", *[f"- `{result.spec}`" for result in passed], ""])
    if failed:
        lines.append("Failed specs:")
        for result in failed:
            lines.append(f"- `{result.spec}` failed with exit code {result.exit_code}")
            if result.error_summary:
                lines.append(f"  - {result.error_summary}")
            if result.log_path:
                lines.append(f"  - Log: `{result.log_path}`")
        lines.append("")
    if skipped:
        lines.extend(["Skipped specs:", *[f"- `{result.spec}`" for result in skipped], ""])
    lines.append("Generated by `gh-spack-pr`.")
    return "\n".join(lines)
